Repository TEAM-DDIS/be14-fin-DDIS-BE, pull requests merged in 2025-06, with the labels that each got.

#12 [FEAT] 급여명세서 조회 (인사) API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/EmployeeMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/DepartmentDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/HeadquartersDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/JobDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/PositionDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/RankDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/TeamDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/controller/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/controller/PayrollQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dao/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dao/SalaryMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/EmployeeSearchCondition.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/EmployeeSummaryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/SalaryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/SalaryDetailDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/SalarySearchCondition.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/SalarySummaryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/service/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/service/EmployeeSearchService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/service/SalaryQueryService.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/EmployeeMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/payroll/query/mapper/SalaryMapper.xml
Labels: ✨ Feat

#13 [REFACTOR] 전자결재 더미데이터 수정
  DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
  DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql
Labels: 🔧 Refactor

#15 [FEAT] 급여 추가 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/EmployeeMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/controller/PayrollQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/service/EmployeeSearchService.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/EmployeeMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/payroll/query/mapper/SalaryMapper.xml
Labels: ✨ Feat

#16 [REFACTOR] 근무 테이블 ddl, dummy 수정
  DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
  DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql
Labels: 🔧 Refactor

#19 [REFACTOR] 전자결재 DDL, 더미데이터 수정
  DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
  DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql
Labels: 🔧 Refactor

#20 [CHORE] 스키마, 더미 수정
  DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
  DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql
Labels: ⚙ Chore

#22 [REFACTOR] 테이블 생성 문자셋 utf8mb4 지정
  DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql
Labels: 🔧 Refactor

#24 [REFACTOR] DDL 수정 selfreview에서 employee_id_reviewer NOT NULL 조건 제거
  DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql
Labels: 🔧 Refactor

#26 [FEAT] 퇴직금 지급현황 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/controller/PayrollQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/controller/RetirementQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dao/RetirementMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/RetirementDetailDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/RetirementSearchCondition.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/RetirementSummaryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/service/RetirementQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/service/RetirementQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/payroll/query/mapper/RetirementMapper.xml
Labels: ✨ Feat, 🔧 Refactor

#27 [FEAT] 리뷰 조회 구현 중
  DDIS_HR/src/main/java/com/ddis/ddis_hr/goals/command/application/dto/GoalDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/review/command/application/controller/ReviewController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/review/command/application/dto/EmployeeReviewDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/review/command/application/mapper/EmployeeReviewMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/review/command/application/service/ReviewService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/review/command/application/service/ReviewServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/review/command/domain/aggregate/Review.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/review/command/domain/aggregate/ReviewGrade.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/review/command/domain/repository/ReviewRepository.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/review/command/application/mapper/EmployeeReviewMapper.xml
  DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
Labels: ✨ Feat

#30 [FEAT] 캘린더 조회 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/controller/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/controller/AttendanceQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dao/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dao/AttendanceMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/AttendanceQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/EmployeeInfoQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/MeetingQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/PersonalCalendarQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/PersonalScheduleQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/TeamCalendarQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/attendance/query/mapper/AttendanceMapper.xml
  DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
Labels: ✨ Feat

#33 [FEAT] 퇴직금 명세서 메일 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/config/ThymeleafConfig.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/command/application/controller/RetirementMailController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/command/application/dto/MonthlySalaryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/command/application/dto/RetirementMailRequestDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/command/application/service/RetirementMailService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/command/application/service/RetirementMailServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/command/application/service/RetirementPdfGenerator.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/controller/RetirementQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/RetirementDetailDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/RetirementSummaryDTO.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/payroll/query/mapper/RetirementMapper.xml
  DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
  DDIS_HR/src/main/resources/templates/payroll/paystub.html
  DDIS_HR/src/main/resources/templates/payroll/retirement.html
Labels: ✨ Feat, 🔧 Refactor

#40 사원 목록 조회 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/EmployeeQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/EmployeeMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeHrDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeListDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeePublicDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/EmployeeQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/EmployeeQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/EmployeeMapper.xml
Labels: ✨ Feat

#47 [FEAT] 오늘 팀 근무 상태, 회의 일정 조회 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/controller/AttendanceQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dao/AttendanceMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/TeamWorkStatusQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/attendance/query/mapper/AttendanceMapper.xml
  DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
  DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql
Labels: ✨ Feat

#48 [FEAT] 내 징계 조회 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/DisciplinaryQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/DisciplinaryMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/MyDisciplinaryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/DisciplinaryQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/DisciplinaryQueryServiceImpl.java
Labels: ✨ Feat

#51 [FEAT] 내 근무 현황 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/controller/AttendanceQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dao/AttendanceMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/MyWorkStatusQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/attendance/query/mapper/AttendanceMapper.xml
Labels: ✨ Feat

#53 [FEAT] 계약서 목록 조회 & 다운로드 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/ContractQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/ContractMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/MyContractDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/ContractQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/ContractQueryServiceImpl.java
Labels: ✨ Feat

#55 [FEAT] 징계 목록 조회 & 다운로드 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/DisciplinaryQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/DisciplinaryMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/DisciplinaryQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/DisciplinaryQueryServiceImpl.java
Labels: ✨ Feat

#57 [FEAT] 전자결재 자동지정 api 구현
  .idea/.gitignore
  .idea/BE.iml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/ApprovalLineQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/ApprovalStepQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/DraftController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/DrafterQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dao/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApprovalLineResponseDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApprovalLineTemplateDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApprovalStepQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApproverInfoQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApproverQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/FindDrafterQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalStepMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/ApproverMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/FindDrafterMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalLineQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalLineQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalStepQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalStepQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DrafterQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DrafterQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalStepMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApproverMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/FindDrafterMapper.xml
Labels: ✨ Feat

#58 [FEAT] 조직 등록 모달 및 인사발령 등록 연동
  DDIS_HR/.gitignore
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/controller/DepartmentController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/controller/HeadquartersController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/controller/StructureController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/controller/TeamController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/dto/DepartmentRequestDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/dto/TeamRequestDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/service/DepartmentServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/service/TeamServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/domain/repository/DepartmentRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/domain/repository/HeadquartersRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/controller/AppointmentHistoryQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/controller/IntroductionQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/controller/StructureQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dao/AppointmentHistoryMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dao/IntroductionMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dao/StructureMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/AppointmentHistoryQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/DepartmentQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/EmployeeQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/HeadQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/TeamQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/service/AppointmentHistoryQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/service/IntroductionQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/service/StructureQueryService.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/organization/query/mapper/Introduction.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/organization/query/mapper/appointment.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/organization/query/mapper/appointmentHistory.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/organization/query/mapper/job.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/organization/query/mapper/structure.xml
  DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
Labels: ✨ Feat

#60 [FEAT] 출퇴근 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/controller/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/controller/AttendanceCommandController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/service/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/service/AttendanceCommandService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/service/AttendanceCommandServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/aggregate/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/aggregate/Attendance.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/aggregate/WorkStatus.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/repository/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/repository/AttendanceEmployeeRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/repository/AttendanceRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/repository/WorkStatusRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/service/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/member/security/JwtUtil.java
  DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql
Labels: ✨ Feat

#66 [FEAT] 메뉴 및 자주 쓰는 메뉴 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/common/CommonResponse.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/common/GlobalExceptionHandler.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/config/WebConfig.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/member/security/WebSecurity.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/application/controller/FavoriteMenuCommandController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/application/dto/FavoriteMenuCommandDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/application/dto/FavoriteMenuOrderChangeDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/application/service/FavoriteMenuCommandService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/application/service/FavoriteMenuCommandServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/domain/aggregate/FavoriteMenu.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/domain/repository/FavoriteMenuRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/domain/service/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/query/controller/FavoriteMenuQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/query/controller/MenuQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/query/dao/FavoriteMenuMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/query/dao/MenuMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/query/dto/FavoriteMenuDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/query/dto/MenuDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/query/service/FavoriteMenuQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/query/service/FavoriteMenuQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/query/service/MenuQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/query/service/MenuQueryServiceImpl.java
  DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
  DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql
Labels: 🎨 Style, ⚙ Chore, ✨ Feat

#69 [FEAT] 기안 문서 생성 api 구현
  DDIS_HR/.gitignore
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/controller/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/controller/DraftCommandController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/dto/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/dto/DraftCreateCommandDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/service/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/service/DraftCommandService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/service/DraftCommandServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/domain/aggregate/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/domain/entity/Draft.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/domain/repository/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/domain/repository/DraftRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/domain/service/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/DraftQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryServiceImpl.java
Labels: ✨ Feat

#70 [FEAT] 메뉴 mapper.xml 추가
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/menu/query/mapper/FavoriteMenuMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/menu/query/mapper/MenuMapper.xml
Labels: ✨ Feat

#71 [FEAT] Spring Batch 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/batch/config/BatchJobConfig.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/batch/scheduler/AppointmentJobScheduler.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/controller/AppointmentHistoryQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/controller/StructureQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dao/StructureMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/service/StructureQueryService.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/organization/query/mapper/appointmentHistory.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/organization/query/mapper/structure.xml
Labels: ✨ Feat

#73 [FEAT] 오늘 개인 일정 조회 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/controller/AttendanceQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dao/AttendanceMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/attendance/query/mapper/AttendanceMapper.xml
Labels: ✨ Feat

#75 [REFACTOR] 결재라인조회 , 기안자 정보조회토큰 활용 코드 수정
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/ApprovalLineQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/DrafterQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/FindDrafterQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/DraftMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/FindDrafterMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalLineQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalLineQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DrafterQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DrafterQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/member/security/JwtUtil.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/FindDrafterMapper.xml
Labels: 🔧 Refactor

#77 [FEAT] 주간 초과 근무 시간 조회 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/controller/AttendanceQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dao/AttendanceMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/WeeklyOvertimeSummaryQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/attendance/query/mapper/AttendanceMapper.xml
Labels: ✨ Feat

#78 [FEAT] 인사발령 등록 시 필요 코드 추가
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/EmployeeQueryDTO.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/organization/query/mapper/IntroductionMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/organization/query/mapper/appointmentHistoryMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/organization/query/mapper/appointmentMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/organization/query/mapper/jobMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/organization/query/mapper/structureMapper.xml
Labels: ✨ Feat

#79 [REFACTOR] fileDTO추가
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/dto/ApprovalLineDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/dto/ApprovalLineRequestDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/dto/DraftCreateCommandDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/dto/DraftCreateResponseCommandDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApproverQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ContentQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DocFormQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/FileQueryDTO.java
Labels: ✨ Feat

#80 [FEAT] 주간 근무 시간 조회 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/controller/AttendanceQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dao/AttendanceMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/WeeklyWorkDurationQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/attendance/query/mapper/AttendanceMapper.xml
Labels: ✨ Feat

#84 [FEAT] 기안 작성 시 사용자별 결재라인 자동생성 및 기안 상신 api 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/controller/DraftCommandController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/service/ApprovalLineCommandService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/service/ApprovalLineCommandServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/service/DraftCommandService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/service/DraftCommandServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/domain/entity/ApprovalLine.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/domain/entity/ApprovalLineType.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/domain/entity/ApprovalType.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/domain/entity/Draft.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/domain/repository/ApprovalLineRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApprovalLineQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApproverInfoQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/ApproverMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalLineQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalLineQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/member/security/JwtUtil.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApproverMapper.xml
Labels: ✨ Feat

#86 [FEAT] 사원 정보 수정 API 구현
  .idea/dataSources.xml
  DDIS_HR/src/main/java/com/ddis/ddis_hr/common/GlobalExceptionHandler.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/controller/EmployeeController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/dto/EmployeeHrUpdateDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/dto/EmployeeUpdateDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/EmployeeService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/EmployeeServiceImpl.java
Labels: ✨ Feat

#92 [FEAT] 연차 관리 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/controller/AttendanceQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dao/AttendanceMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/AllLeaveHistoryQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/LeaveHistoryQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/LeaveStatusQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/attendance/query/mapper/AttendanceMapper.xml
Labels: ✨ Feat

#96 [FEAT] 결재함 결재 조회 생성
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/dto/DraftCreateCommandDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/service/ApprovalLineCommandServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/domain/entity/ApprovalLine.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/ApprovalDocumentQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/ApprovalLineQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/DraftQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DocumentDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/DraftDocumentMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalDocumentQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalDocumentQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/DraftDocumentMapper.xml
Labels: ✨ Feat

#100 [FEAT] 알림 조회 및 발송 구현
  DDIS_HR/build.gradle
  DDIS_HR/src/main/java/com/ddis/ddis_hr/DdisHrApplication.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/application/config/WebSocketConfig.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/application/controller/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/application/controller/NoticeController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/application/dto/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/application/dto/NoticeDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/application/event/NoticeEvent.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/application/listener/NoticeEventListener.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/application/service/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/application/service/NoticeService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/application/service/NoticeServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/domain/aggregate/NoticeEntity.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/domain/repository/NoticeRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/domain/service/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/query/controller/NoticeQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/query/dao/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/query/dao/NoticeMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/query/dto/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/query/dto/NoticeQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/query/service/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/query/service/NoticeQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/batch/config/BatchJobConfig.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/batch/domain/AppointmentHistory.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/batch/listener/AppointmentHistoryNoticeListener.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/batch/listener/JobCompletionNotificationListener.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/notice/query/mapper/NoticeMapper.xml
Labels: ✨ Feat

#103 [FEAT] 결재함 조회
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DraftDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/DraftDocumentMapper.xml
Labels: ✨ Feat

#104 [REFACTOR] S3 로직 추가
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/controller/EmployeeController.java
Labels: 🔧 Refactor

#106 [FEAT] 용어사전 조회 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/dictionary/query/controller/DictionaryQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/dictionary/query/dao/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/dictionary/query/dao/DictionaryMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/dictionary/query/dto/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/dictionary/query/dto/DictionaryQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/dictionary/query/service/DictionaryQueryService.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/dictionary/query/mapper/DictionaryMapper.xml
Labels: ✨ Feat

#108 [REFACTOR] gitignore 수정
  .gitignore
Labels: 🔧 Refactor

#112 [FEAT] 출근 정정 관리 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/controller/AttendanceCommandController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/dto/AttendanceApproveRequestDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/dto/AttendanceCorrectionRequestDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/dto/AttendanceRejectRequestDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/service/AttendanceCommandService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/service/AttendanceCommandServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/aggregate/Attendance.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/repository/AttendanceRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/controller/AttendanceQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dao/AttendanceMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/AllCommuteCorrectionQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/MyCommuteCorrectionQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/attendance/query/mapper/AttendanceMapper.xml
  DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql
Labels: ✨ Feat

#113 [FEAT] 사원 생일 추가
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeListDTO.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/EmployeeMapper.xml
Labels: ✨ Feat

#114 [REFACTOR] 근무상태별 출퇴근 등록 조건 변경, 근무시간 등록 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/service/AttendanceCommandServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/aggregate/Attendance.java
Labels: 🔧 Refactor

#115 [FEAT] 결근 처리 스케줄러 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/DdisHrApplication.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/scheduler/AbsenceScheduler.java
Labels: ✨ Feat

#118 [FEAT] 사원 등록 백 프론트 연동, 스키마 & 더미데이터 수정
  DDIS_HR/.gitignore
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/controller/EmployeeController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/dto/EmployeeEnrollDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/dto/EmployeeHrUpdateDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeHrDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeePublicDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/member/command/application/dto/EmployeeDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/member/command/domain/aggregate/entity/Employee.java
  DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
  DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql
Labels: ✨ Feat

#121 [FEAT] 전자결재 결재함 구현 api
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/ApprovalDocumentQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/ApprovalLineQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/DraftQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/DrafterQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApprovalLineQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApprovalLineResponseDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApprovalLineTemplateDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DocumentDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DraftDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DraftDetailResponseQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/DraftDocumentMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/DraftMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalDocumentQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalDocumentQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DrafterQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/DraftMapper.xml
Labels: ✨ Feat

#124 [REFACTOR] 사원 정보 상세 조회
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/controller/EmployeeController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/EmployeeQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/EmployeeMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/EmployeeQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/EmployeeQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/EmployeeMapper.xml
Labels: 🔧 Refactor

#127 [FEAT] 사내문서 S3 업로드, 다운로드, 조회 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/command/application/controller/PolicyPdfQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/command/application/controller/PolicyPdfUploadController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/command/application/dto/PolicyFileDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/command/application/dto/UploadPolicyDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/command/application/service/PolicyPdfQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/command/application/service/PolicyPdfQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/command/application/service/PolicyPdfUploadService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/command/application/service/PolicyPdfUploadServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/command/domain/aggregate/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/command/domain/repository/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/command/domain/service/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/query/controller/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/query/dao/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/query/dto/.gitkeep
  DDIS_HR/src/main/java/com/ddis/ddis_hr/chatbot/query/service/.gitkeep
  DDIS_HR/src/main/resources/templates/policy/annual_leave.html
  DDIS_HR/src/main/resources/templates/policy/bonus_policy.html
  DDIS_HR/src/main/resources/templates/policy/discipline.html
  DDIS_HR/src/main/resources/templates/policy/document_mgmt.html
  DDIS_HR/src/main/resources/templates/policy/family_event.html
  DDIS_HR/src/main/resources/templates/policy/handover.html
  DDIS_HR/src/main/resources/templates/policy/job_transfer.html
  DDIS_HR/src/main/resources/templates/policy/leave_policy.html
  DDIS_HR/src/main/resources/templates/policy/overtime_comp.html
  DDIS_HR/src/main/resources/templates/policy/performance_evaluation.html
  DDIS_HR/src/main/resources/templates/policy/personnel_policy.html
  DDIS_HR/src/main/resources/templates/policy/promotion.html
  DDIS_HR/src/main/resources/templates/policy/salary_policy.html
  DDIS_HR/src/main/resources/templates/policy/severance.html
  DDIS_HR/src/main/resources/templates/policy/severance_interim.html
  DDIS_HR/src/main/resources/templates/policy/software_manual.html
  DDIS_HR/src/main/resources/templates/policy/welfare.html
  DDIS_HR/src/main/resources/templates/policy/work_discipline.html
Labels: ✨ Feat

#128 [FIX] DisciplinaryListDTO 주석 처리
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/DisciplinaryQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/DisciplinaryMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/DisciplinaryQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/DisciplinaryQueryServiceImpl.java
Labels: 🔨 Fix

#131 [FEAT] 초과 근무 신청 API 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/controller/AttendanceCommandController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/dto/OvertimeRequestDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/service/AttendanceCommandService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/service/AttendanceCommandServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/repository/AttendanceRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/attendance/query/mapper/AttendanceMapper.xml
Labels: ✨ Feat

#133 [REFACTOR] 전자결재 결재라인 및 문서함, 결재처리 리팩토링
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/service/ApprovalLineCommandService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/service/ApprovalLineCommandServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/service/DraftCommandServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/ApprovalDocumentQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/ApprovalLineQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/ApprovalStepQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/DraftQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApproverInfoQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DocumentDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DraftDetailResponseQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/FindDrafterQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalStepMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/ApproverMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/DraftDocumentMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/FindDrafterMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalDocumentQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalDocumentQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalLineAutoMatchService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalLineAutoMatchServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalLineQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalLineQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalStepQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalStepQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalStepMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApproverMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/DraftMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/FindDrafterMapper.xml
  DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
  DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql
  DDIS_HR/src/test/java/com/ddis/ddis_hr/eapproval/service/ApprovalLineAutoMatchServiceTest.java
Labels: 🔨 Fix, ✨ Feat, 🔧 Refactor, ✅ Test

#136 [FEAT] 전자결재 회수 api 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/DraftQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DocumentDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/DraftMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/DraftMapper.xml
Labels: ✨ Feat

#139 [REFACTOR] 급여 권한 설정 및 api 수정
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/command/application/controller/PayrollMailController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/command/application/controller/RetirementMailController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/controller/PayrollQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/controller/RetirementQueryController.java
Labels: 🔧 Refactor

#141 [FEAT] 연차 지급/촉진 스케줄러 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/scheduler/AbsenceScheduler.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/scheduler/AttendanceScheduler.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/aggregate/Leave.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/aggregate/LeaveAlertLog.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/repository/LeaveAlertLogRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/repository/LeaveRepository.java
Labels: ✨ Feat

#153 [REFACTOR] 근태 API 권한 설정
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/controller/AttendanceCommandController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/controller/AttendanceQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/TeamWorkStatusQueryDTO.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/attendance/query/mapper/AttendanceMapper.xml
Labels: 🔧 Refactor

#161 [REFACTOR] 백엔드 연동을 위한 매퍼 수정, 오류 코드 주석 처리
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/controller/DraftCommandController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeListDTO.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/EmployeeMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/organization/query/mapper/appointmentHistoryMapper.xml
Labels: 🔨 Fix, 🔧 Refactor

#163 [REFACTOR] 사원 조회 권한 설정
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/controller/EmployeeController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/dto/EmployeeHrUpdateDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/EmployeeService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/EmployeeServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/EmployeeQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/EmployeeQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/EmployeeQueryServiceImpl.java
Labels: 🔧 Refactor

#164 [FEAT] 인사팀 권한 설정
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/controller/AppointmentController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/controller/IntroductionController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/controller/JobController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/controller/StructureController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/controller/AppointmentQueryController.java
  DDIS_HR/src/test/java/com/ddis/ddis_hr/organization/TeamRegisterTests.java
Labels: ✨ Feat

#167 [REFACTOR] 자주 쓰는 메뉴 api 방식 변경
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/application/controller/FavoriteMenuCommandController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/application/dto/FavoriteMenuOrderChangeDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/application/service/FavoriteMenuCommandServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/domain/aggregate/FavoriteMenu.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/domain/repository/FavoriteMenuRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/query/controller/FavoriteMenuQueryController.java
Labels: ✨ Feat, 🔧 Refactor

#169 [FEAT] 기안문 상세조회 내 수신자, 참조자 렌더링 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/dto/DraftCreateCommandDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DocumentDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/DraftMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftDetailService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftDetailServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/DocumentBoxMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/DraftMapper.xml
Labels: ✨ Feat

#172 [REFACTOR] 백엔드 권한 설정
  DDIS_HR/src/main/java/com/ddis/ddis_hr/board/command/application/controller/BoardController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/board/command/application/dto/BoardCreateDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/board/command/application/dto/BoardUpdateDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/board/command/application/service/BoardServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/controller/ContractController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/controller/DisciplinaryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/controller/EmployeeController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/dto/ContractEnrollDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/dto/DisciplinaryEnrollDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/dto/EmployeeEnrollDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/dto/EmployeeUpdateDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/ContractServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/DisciplinaryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/DisciplinaryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/EmployeeService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/EmployeeServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/domain/aggregate/Contract.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/domain/aggregate/ContractFile.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/domain/aggregate/Disciplinary.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/domain/repository/ContractRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/domain/repository/EmployeesRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/ContractQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/DisciplinaryQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/EmployeeQueryController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/ContractMapper.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/DisciplinaryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeHrDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeePublicDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeSearchDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/MyDisciplinaryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/ContractQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/ContractQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/DisciplinaryQueryService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/DisciplinaryQueryServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/EmployeeQueryServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/board/query/mapper/BoardMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/ContractMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/DisciplinaryMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/EmployeeMapper.xml
Labels: 🔧 Refactor

#173 [REFACTOR] 알림, 용어사전 더미 수정
  DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
  DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql
Labels: 🔧 Refactor

#176 [FEAT] github action을 위한 yml 추가
  .github/workflows/cr.yml
  .gitignore
  DDIS_HR/.ebextensions/app.config
  DDIS_HR/.platform/nginx.conf
  DDIS_HR/Procfile
  DDIS_HR/build.gradle
Labels: ✨ Feat

#182 [FEAT] 배포 버전 중복 방지
  .github/workflows/cr.yml
Labels: ✨ Feat

#183 [REFACTOR] EOL -> EOF
  .github/workflows/cr.yml
Labels: 🔧 Refactor

#184 [FEAT] 배포 테스트
  .github/workflows/cr.yml
Labels: ✨ Feat

#193 [FEAT] 사원 등록,수정 낙관적 lock 적용
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/EmployeeServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/domain/repository/EmployeesRepository.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/member/command/domain/aggregate/entity/Employee.java
  DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql
Labels: ✨ Feat, 🔧 Refactor

#194 [TEST] 낙관적 Lock 테스트 코드 추가
  DDIS_HR/src/test/java/com/ddis/ddis_hr/employee/EmployeeOptimisticLockTest.java
Labels: ✅ Test

#198 [REFACTOR] 평가 점수가 비정상적으로 튀는 버그 수정
  DDIS_HR/api-docs.json
  DDIS_HR/api-docs.yaml
  DDIS_HR/build.gradle
  DDIS_HR/generated-docs/.openapi-generator-ignore
  DDIS_HR/generated-docs/.openapi-generator/FILES
  DDIS_HR/generated-docs/.openapi-generator/VERSION
  DDIS_HR/generated-docs/index.html
  DDIS_HR/settings.gradle
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/controller/DraftCommandController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/goals/command/application/controller/GoalController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/goals/command/application/dto/GoalDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/goals/command/application/service/PerformanceServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/review/command/application/controller/ReviewController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/review/command/application/service/ReviewServiceImpl.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/goals/command/application/mapper/GoalsMapper.xml
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/review/command/application/mapper/PerformanceHistoryMapper.xml
  DDIS_HR/src/test/java/com/ddis/ddis_hr/payroll/command/application/service/PayrollMailServiceImplDiffblueTest.java
Labels: 🔧 Refactor

#200 [FEAT] 사내 문서 업로드용 api 구현
  DDIS_HR/src/main/java/com/ddis/ddis_hr/S3Config/controller/S3Controller.java
Labels: ✨ Feat

#205 [FEAT] 기안 등록 시 결재 요청 알림
  DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/scheduler/AttendanceScheduler.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/service/DraftCommandServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/application/event/NoticeEvent.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/application/listener/NoticeEventListener.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/domain/aggregate/NoticeEntity.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/batch/listener/AppointmentHistoryNoticeListener.java
Labels: ✨ Feat

#215 [FEAT] 헤더 프로필 url 추가
  DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeListDTO.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/EmployeeMapper.xml
Labels: ✨ Feat

#219 [REFACTOR] 전자결재 리팩토링
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApprovalStepQueryDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DocumentDTO.java
  DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.xml
Labels: 🔧 Refactor

#220 [REFACTOR] 직무 소개 수정 코드 리팩토링
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/batch/config/BatchJobConfig.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/batch/scheduler/AppointmentJobScheduler.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/controller/JobController.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/dto/JobRequestDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/dto/JobResponseDTO.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/service/AppointmentServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/service/JobService.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/service/JobServiceImpl.java
  DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/domain/aggregate/entity/AppointmentEntity.java
  DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
Labels: 🔧 Refactor
